'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'
import './shop.css'
const money=new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0})
function Icon({type}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">{type==='shop'?<path d="M3 10h18L19 3H5l-2 7Zm2 0v11h14V10M9 21v-7h6v7"/>:type==='orders'?<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></>:<><circle cx="12" cy="7" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>}</svg>}
export default function Shop(){
 const [tab,setTab]=useState('shop'),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[offset,setOffset]=useState(0),[stores,setStores]=useState([]),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0),[session,setSession]=useState(null),[authReady,setAuthReady]=useState(false),[orders,setOrders]=useState([]),[dark,setDark]=useState(false)
 useEffect(()=>{const d=localStorage.getItem('orderflow-theme')==='dark';setDark(d);document.documentElement.dataset.theme=d?'dark':'light';if(!supabase){setAuthReady(true);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true)});const {data}=supabase.auth.onAuthStateChange((_,s)=>{setSession(s);setAuthReady(true)});return()=>data.subscription.unsubscribe()},[])
 useEffect(()=>{let active=true;setLoading(true);setError('');const timer=setTimeout(async()=>{try{if(!supabase)throw Error();if(tab==='shop'){const {data,error}=await supabase.rpc('search_public_stores',{p_search:search.trim(),p_category:category,p_offset:offset});if(error)throw error;if(active){setStores((data||[]).slice(0,12));setMore((data||[]).length>12)}}else if(tab==='orders'&&session){const {data,error}=await supabase.rpc('get_buyer_saved_orders');if(error)throw error;if(active)setOrders(data||[])} }catch{if(active)setError('We couldn’t load this page. Please try again.')}finally{if(active)setLoading(false)}},tab==='shop'?250:0);return()=>{active=false;clearTimeout(timer)}},[tab,search,category,offset,retry,session])
 return <main className="shop-app"><header className="shop-header"><a href="/shop" className="shop-brand">Order<span>Flow</span></a><div>{authReady&&!session&&<a href="/buyer">Sign in</a>}<button aria-label="Switch theme" onClick={()=>{const d=!dark;setDark(d);document.documentElement.dataset.theme=d?'dark':'light';localStorage.setItem('orderflow-theme',d?'dark':'light')}}>{dark?'☀':'◐'}</button></div></header><section className="shop-content">
 {tab==='shop'?<><small className="shop-eyebrow">A little discovery. A great find.</small><h1>Find your next favourite store.</h1><p>Browse vendors, explore their products and shop at your pace.</p><label className="shop-search"><span>Search vendors</span><input type="search" placeholder="Search by store name…" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0)}}/></label><div className="shop-categories" aria-label="Store categories">{['','Fashion','Beauty','Food & drinks','Electronics','Home & living','Health','Services','Other'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>{setCategory(c);setOffset(0)}}>{c||'All stores'}</button>)}</div><h2>Discover stores</h2>{!loading&&!error&&(stores.length?<><div className="shop-grid">{stores.map(s=><article className="shop-store" key={s.merchant_id}><div className="shop-previews">{s.previews.map(p=><div key={p.id}>{p.image_url?<img src={p.image_url} alt={p.name} loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/>:<div className="shop-image-placeholder"><Icon type="shop"/></div>}<span>{p.name}</span><small>{money.format(p.price)}</small></div>)}</div><div className="shop-store-footer"><div><h3>{s.business_name}</h3><p>{s.product_count} product{Number(s.product_count)===1?'':'s'}</p></div><a href={`/?store=${encodeURIComponent(s.merchant_id)}`}>Visit store →</a></div></article>)}</div><div className="shop-pagination"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-12))}>Previous</button><span>Page {offset/12+1}</span><button disabled={!more} onClick={()=>setOffset(offset+12)}>Next</button></div></>:<div className="shop-empty"><h3>{search||category?'No matching stores':'Stores are on their way'}</h3><p>{search||category?'Try another name or choose All stores.':'Vendors with published products will appear here.'}</p></div>)}</>:tab==='orders'?<><h1>My orders</h1><p>Your saved orders, across stores.</p>{authReady&&!session?<a className="shop-cta" href="/buyer">Sign in to your buyer account</a>:!loading&&!error&&(orders.length?orders.map(o=><a className="shop-order" key={o.public_token} href={`/?track=${encodeURIComponent(o.public_token)}`}><span>{o.order_number}<small>{o.business_name}</small></span><span>{o.status}<small>Track order →</small></span></a>):<p>No saved orders yet. Orders placed while signed in, or saved from the payment-success screen, will appear here.</p>)}</>:<><h1>Your account</h1>{!authReady?<p>Loading account…</p>:session?<><p>{session.user.email}</p><button className="shop-cta" onClick={async()=>{const {error}=await supabase.auth.signOut();if(error)setError('Could not sign out. Please try again.')}}>Sign out</button></>:<><p>Sign in to keep your orders in one place.</p><a className="shop-cta" href="/buyer">Sign in</a><a className="shop-secondary" href="/buyer?mode=signup">Create a buyer account</a></>}</>}
 {loading&&tab!=='account'&&<p role="status">Loading…</p>}{error&&<div role="alert" className="shop-empty"><p>{error}</p><button onClick={()=>setRetry(n=>n+1)}>Try again</button></div>}</section><nav className="shop-nav" aria-label="Buyer navigation">{[['shop','Shop'],['orders','My orders'],['account','Account']].map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>setTab(key)}><Icon type={key}/><span>{label}</span></button>)}</nav></main>
}
